Label migration
outscale-dev/osc-bsu-csi-driver pull request #206
Opened 2022-05-19 07:49 UTC by outscale-mdr

Change all referecenes and label to outscale labels

Close #88 
Close #87

2022-08-25 14:21 UTC, jerome-jutteau requested changes

2022-08-25 14:21 UTC, jerome-jutteau commented on docs/storageclass.md
> +* `type`: `standard`, gp2, `io1`. See
gp2 -> \`gp2\` ?

2022-08-25 14:21 UTC, jerome-jutteau commented on docs/storageclass.md
> +  A string is expected here, i.e. `"10"`, not `10`.
maybe to be fixed for 1.0: can't we have an integer here?

2022-08-25 14:21 UTC, jerome-jutteau commented on examples/kubernetes/static-provisioning/README.md
>            - us-east-1c
we can set an existing zone for Outscale like us-east-2a or eu-west-2a

2022-08-25 14:21 UTC, jerome-jutteau commented on examples/kubernetes/storageclass/README.md
> +1. Edit the StorageClass spec in [example manifest](./specs/example.yaml) and update storageclass parameters to desired value. In this example, a `io1` BSU volume will be created and formatted to `xf
I think we can remove KMS mention for now

2022-08-25 14:21 UTC, jerome-jutteau commented on docs/migration.md
> +To make things smoothe, here a guide to migrate from the two versions
smooth :)

2022-08-25 14:21 UTC, jerome-jutteau commented on docs/migration.md
> +Having a 0.0.X CSI driver installed
0.x.x ?

2022-08-25 14:21 UTC, jerome-jutteau commented on docs/migration.md
> +> **Note**: You should be able to install both 0.0.X and 1.0.0 plugins as drivers names differ
same

2022-08-26 09:28 UTC, outscale-mdr commented on docs/storageclass.md
> +  A string is expected here, i.e. `"10"`, not `10`.
It is a kubernetes restriction (See [docs](https://github.com/kubernetes/api/blob/3be0a3c7fb9e94e3694f41b538eceb358f93d889/storage/v1/types.go#L47))

2022-08-29 08:07 UTC, jerome-jutteau approved these changes

2022-08-29 08:08 UTC, merged